/**
 * Smart Switches
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorDetail } from '../models/ErrorDetail';
import { HttpFile } from '../http/http';

export class ErrorModel {
    /**
    * A URL to the JSON Schema for this object.
    */
    'schema'?: string;
    /**
    * A human-readable explanation specific to this occurrence of the problem.
    */
    'detail'?: string;
    /**
    * Optional list of individual error details
    */
    'errors'?: Array<ErrorDetail> | null;
    /**
    * A URI reference that identifies the specific occurrence of the problem.
    */
    'instance'?: string;
    /**
    * HTTP status code
    */
    'status'?: number;
    /**
    * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
    */
    'title'?: string;
    /**
    * A URI reference to human-readable documentation for the error.
    */
    'type'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "string",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ErrorDetail>",
            "format": ""
        },
        {
            "name": "instance",
            "baseName": "instance",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return ErrorModel.attributeTypeMap;
    }

    public constructor() {
    }
}
