/**
 * Smart Switches
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Command } from '../models/Command';
import { HttpFile } from '../http/http';

export class LayoutInstance {
    'buttons': { [key: string]: Command; };
    'flipped': boolean;
    'version': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "buttons",
            "baseName": "buttons",
            "type": "{ [key: string]: Command; }",
            "format": ""
        },
        {
            "name": "flipped",
            "baseName": "flipped",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LayoutInstance.attributeTypeMap;
    }

    public constructor() {
    }
}
