/**
 * Smart Switches
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LayoutDefinition {
    'Buttons': Array<string> | null;
    'Description': string;
    'Version': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "Buttons",
            "baseName": "Buttons",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "Description",
            "baseName": "Description",
            "type": "string",
            "format": ""
        },
        {
            "name": "Version",
            "baseName": "Version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LayoutDefinition.attributeTypeMap;
    }

    public constructor() {
    }
}
