/**
 * Smart Switches
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Executable } from '../models/Executable';
import { HttpFile } from '../http/http';

export class ListExecutablesResponseBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    'schema'?: string;
    'executables': { [key: string]: Executable; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "executables",
            "baseName": "executables",
            "type": "{ [key: string]: Executable; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListExecutablesResponseBody.attributeTypeMap;
    }

    public constructor() {
    }
}
