/**
 * Smart Switches
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PostPressRequestBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    'schema'?: string;
    'key': string;
    'layout': string;
    '_switch': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "layout",
            "baseName": "layout",
            "type": "string",
            "format": ""
        },
        {
            "name": "_switch",
            "baseName": "switch",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PostPressRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}
