/**
 * Smart Switches
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LayoutInstance } from '../models/LayoutInstance';
import { HttpFile } from '../http/http';

export class Switch {
    'layouts': { [key: string]: LayoutInstance; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "layouts",
            "baseName": "layouts",
            "type": "{ [key: string]: LayoutInstance; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Switch.attributeTypeMap;
    }

    public constructor() {
    }
}
